<?php
$title = 'Delete school';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete '<?php echo $this->escapeHtml($school->name); ?>'?</p>

<?php
$url = $this->url('school', array(
 'action' => 'delete',
 'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post" role="form">
    <div class="form-group">
        <input type="hidden" name="id" value="<?php echo (int) $school->id; ?>" />
        <input class="btn btn-default" type="submit" name="del" value="Yes" />
        <input class="btn btn-default" type="submit" name="del" value="No" />
    </div>
</form>