<?php
$title = 'Schools';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php 
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
     ->setMessageSeparatorString('</li><li>')
     ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>


<p>
    <a class="btn btn-primary btn-sm" href="<?php echo $this->url('school', array('action'=>'add'));?>">Add new school</a>
</p>

<table class="table">
<tr>
    <th>Code</th>
    <th>Name</th>
    <th>Address</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($schools as $school) : ?>
<tr>
    <td><?php echo $this->escapeHtml($school->code);?></td>
    <td><?php echo $this->escapeHtml($school->name);?></td>
    <td><?php echo $this->escapeHtml($school->address);?></td>    
    <td>
        <a class="btn btn-default btn-xs" href="<?php echo $this->url('school',
            array('action'=>'edit', 'id' => $school->id));?>">Edit</a>
        <a class="btn btn-default btn-xs" href="<?php echo $this->url('school',
            array('action'=>'delete', 'id' => $school->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>